-- Style Match MVP — seed data
-- ~30 looks per gender (~60 total), 6 per archetype per gender.
-- Image URLs are placeholders; replace once a real catalog exists.

insert into public.looks
    (gender_pathway, archetype, name, description, image_url, size_range, style_tags, color_tags, occasion_tags, budget_tier)
values
    -- ============================================================
    -- MEN'S — Modern Minimalist
    -- ============================================================
    ('mens', 'Modern Minimalist', 'The Weekend Editor',
     'Soft merino crewneck over straight-leg charcoal trousers. Pared-back, photo-ready everywhere.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+1',
     array['S','M','L','XL'], array['minimalist','classic'], array['neutrals','monochrome'], array['casual','work'], 'mid'),
    ('mens', 'Modern Minimalist', 'Monochrome Commuter',
     'Black tee, black overshirt, black trousers. The uniform reduced to its essentials.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+2',
     array['XS','S','M','L','XL'], array['minimalist'], array['monochrome'], array['work','casual'], 'premium'),
    ('mens', 'Modern Minimalist', 'Quiet Luxe Layers',
     'Heavyweight cotton tee under a stone-colored cashmere cardigan. Whisper, not shout.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+3',
     array['S','M','L','XL','XXL'], array['minimalist','classic'], array['neutrals'], array['work','casual'], 'premium'),
    ('mens', 'Modern Minimalist', 'Essential Tee & Trouser',
     'Boxy white tee tucked into pleated bone trousers. Clean lines, zero logos.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+4',
     array['XS','S','M','L','XL','XXL'], array['minimalist'], array['neutrals'], array['casual'], 'budget'),
    ('mens', 'Modern Minimalist', 'Crisp Office Standard',
     'Crisp oxford shirt, slim navy chinos, lace-up derbies. Office-ready without trying.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+5',
     array['S','M','L','XL'], array['classic','minimalist'], array['neutrals'], array['work'], 'mid'),
    ('mens', 'Modern Minimalist', 'Sunday Slow Look',
     'Slate hoodie, matching sweatpants, off-white sneakers. A muted Sunday in three pieces.',
     'https://placehold.co/600x800?text=Mens+Modern+Minimalist+6',
     array['S','M','L','XL','XXL'], array['minimalist'], array['monochrome'], array['casual'], 'budget'),

    -- ============================================================
    -- MEN'S — Classic Preppy
    -- ============================================================
    ('mens', 'Classic Preppy', 'Boathouse Captain',
     'Cream cable-knit sweater, navy chinos, boat shoes. Sailing club on or off the water.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+1',
     array['S','M','L','XL'], array['preppy','classic'], array['neutrals','jewel_tones'], array['casual','formal'], 'mid'),
    ('mens', 'Classic Preppy', 'Library Hours',
     'Tweed blazer over a button-down with knit tie. Wear it where the books are old.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+2',
     array['S','M','L','XL','XXL'], array['preppy','classic'], array['neutrals'], array['work','formal'], 'premium'),
    ('mens', 'Classic Preppy', 'Game Day Tailor',
     'Burgundy quarter-zip, khakis, leather loafers. Saturday in the stands, Sunday on campus.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+3',
     array['S','M','L','XL'], array['preppy','classic'], array['jewel_tones','neutrals'], array['casual'], 'mid'),
    ('mens', 'Classic Preppy', 'Sunday Brunch Blazer',
     'Unstructured navy blazer over a pastel oxford, finished with white denim.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+4',
     array['S','M','L','XL'], array['preppy','classic'], array['neutrals','jewel_tones'], array['casual','formal'], 'premium'),
    ('mens', 'Classic Preppy', 'The Heritage Knit',
     'Forest-green Shetland sweater, cord trousers, suede chukkas. Heritage in three pieces.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+5',
     array['XS','S','M','L','XL'], array['preppy'], array['jewel_tones','earth_tones'], array['casual','work'], 'mid'),
    ('mens', 'Classic Preppy', 'Polished Polo Day',
     'Fitted polo, woven belt, tailored shorts in summer or chinos in fall.',
     'https://placehold.co/600x800?text=Mens+Classic+Preppy+6',
     array['XS','S','M','L','XL','XXL'], array['preppy','classic'], array['neutrals'], array['work','casual'], 'budget'),

    -- ============================================================
    -- MEN'S — Streetwear Casual
    -- ============================================================
    ('mens', 'Streetwear Casual', 'Hype Drop Hero',
     'Graphic boxy tee, cargo pants, chunky sneakers. Built for the line and the after-party.',
     'https://placehold.co/600x800?text=Mens+Streetwear+1',
     array['S','M','L','XL'], array['streetwear'], array['brights','monochrome'], array['going_out','casual'], 'mid'),
    ('mens', 'Streetwear Casual', 'Athleisure A-Train',
     'Tech-fleece hoodie, joggers with zip cuffs, low-top runners. Commute mode engaged.',
     'https://placehold.co/600x800?text=Mens+Streetwear+2',
     array['S','M','L','XL','XXL'], array['athleisure','streetwear'], array['monochrome'], array['casual','athletic'], 'mid'),
    ('mens', 'Streetwear Casual', 'Skate Park Standard',
     'Faded tee, loose carpenter pants, vulcanized skate shoes. Bruised but composed.',
     'https://placehold.co/600x800?text=Mens+Streetwear+3',
     array['XS','S','M','L','XL'], array['streetwear'], array['brights','neutrals'], array['casual','going_out'], 'budget'),
    ('mens', 'Streetwear Casual', 'Tech Layer Set',
     'Matte black shell jacket over a long-line tee and tapered tech pants.',
     'https://placehold.co/600x800?text=Mens+Streetwear+4',
     array['S','M','L','XL'], array['athleisure','streetwear'], array['monochrome'], array['casual','athletic'], 'premium'),
    ('mens', 'Streetwear Casual', 'Late Night Sneakerhead',
     'All-black hoodie, slim joggers, statement sneakers. Built around the kicks.',
     'https://placehold.co/600x800?text=Mens+Streetwear+5',
     array['S','M','L','XL','XXL'], array['streetwear'], array['monochrome'], array['going_out','casual'], 'mid'),
    ('mens', 'Streetwear Casual', 'Sunday Run & Coffee',
     'Bright performance tee, lightweight shorts, runners that double as everyday shoes.',
     'https://placehold.co/600x800?text=Mens+Streetwear+6',
     array['XS','S','M','L','XL','XXL'], array['athleisure'], array['brights','monochrome'], array['athletic','casual'], 'budget'),

    -- ============================================================
    -- MEN'S — Bohemian Relaxed
    -- ============================================================
    ('mens', 'Bohemian Relaxed', 'Desert Wanderer',
     'Open-weave linen shirt, sand-colored drawstring trousers, leather sandals.',
     'https://placehold.co/600x800?text=Mens+Bohemian+1',
     array['S','M','L','XL'], array['bohemian'], array['earth_tones'], array['casual','going_out'], 'mid'),
    ('mens', 'Bohemian Relaxed', 'Festival Lightweight',
     'Soft cotton henley, drawstring pants, woven crossbody bag for the long day out.',
     'https://placehold.co/600x800?text=Mens+Bohemian+2',
     array['XS','S','M','L','XL'], array['bohemian','minimalist'], array['earth_tones','pastels'], array['going_out','casual'], 'budget'),
    ('mens', 'Bohemian Relaxed', 'Linen Drifter',
     'Heavyweight linen camp shirt, wide-leg trousers, espadrilles. Mediterranean defaults.',
     'https://placehold.co/600x800?text=Mens+Bohemian+3',
     array['S','M','L','XL','XXL'], array['bohemian'], array['earth_tones'], array['casual'], 'premium'),
    ('mens', 'Bohemian Relaxed', 'Coastal Cabin',
     'Faded chambray shirt, washed pastel trousers, beat-up canvas sneakers.',
     'https://placehold.co/600x800?text=Mens+Bohemian+4',
     array['S','M','L','XL'], array['bohemian','minimalist'], array['pastels','earth_tones'], array['casual','going_out'], 'mid'),
    ('mens', 'Bohemian Relaxed', 'Slow Mornings Knit',
     'Hand-loomed cardigan, raw-edge tee, wide cord trousers. Built for unrushed days.',
     'https://placehold.co/600x800?text=Mens+Bohemian+5',
     array['XS','S','M','L','XL'], array['bohemian'], array['earth_tones'], array['casual'], 'mid'),
    ('mens', 'Bohemian Relaxed', 'Open Road Layers',
     'Faded denim shirt, mock-neck tee, sand-colored chinos. Road-trip uniform.',
     'https://placehold.co/600x800?text=Mens+Bohemian+6',
     array['S','M','L','XL','XXL'], array['bohemian'], array['earth_tones','pastels'], array['casual'], 'budget'),

    -- ============================================================
    -- MEN'S — Polished Edgy
    -- ============================================================
    ('mens', 'Polished Edgy', 'Black Tie Rebel',
     'Slim tuxedo jacket, black silk tee underneath, polished Chelsea boots.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+1',
     array['S','M','L','XL'], array['edgy','classic'], array['monochrome','jewel_tones'], array['formal','going_out'], 'premium'),
    ('mens', 'Polished Edgy', 'After Hours Architect',
     'Long-line wool coat over an all-black layered look. Built for cold rooftops.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+2',
     array['S','M','L','XL','XXL'], array['edgy','classic'], array['monochrome'], array['going_out','work'], 'premium'),
    ('mens', 'Polished Edgy', 'Studio Sharp',
     'Black turtleneck, slim trousers, leather derby. Quiet in the room, loud in the photos.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+3',
     array['XS','S','M','L','XL'], array['edgy','minimalist'], array['monochrome'], array['work','going_out'], 'mid'),
    ('mens', 'Polished Edgy', 'Neon Hour Suit',
     'Deep emerald velvet blazer, black trousers, patent loafers. Calibrated for night.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+4',
     array['S','M','L','XL'], array['edgy','classic'], array['jewel_tones','monochrome'], array['going_out','formal'], 'premium'),
    ('mens', 'Polished Edgy', 'Gallery Opening',
     'Asymmetric black overshirt, raw-hem trousers, square-toe boots. For long openings.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+5',
     array['S','M','L','XL'], array['edgy'], array['monochrome'], array['going_out','formal'], 'mid'),
    ('mens', 'Polished Edgy', 'Steel & Leather',
     'Leather biker jacket, charcoal tee, dark selvedge denim. Polished, not pristine.',
     'https://placehold.co/600x800?text=Mens+Polished+Edgy+6',
     array['XS','S','M','L','XL','XXL'], array['edgy'], array['monochrome'], array['going_out'], 'mid'),

    -- ============================================================
    -- WOMEN'S — Modern Minimalist
    -- ============================================================
    ('womens', 'Modern Minimalist', 'Capsule Curator',
     'Bone trousers, ivory silk tank, soft trench layered on cold mornings.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+1',
     array['XS','S','M','L'], array['minimalist','classic'], array['neutrals'], array['work','casual'], 'premium'),
    ('womens', 'Modern Minimalist', 'The Editor''s Trench',
     'Camel trench over a black turtleneck and tailored trousers. The cover-of-the-book look.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+2',
     array['XS','S','M','L','XL'], array['minimalist','classic'], array['neutrals','monochrome'], array['work'], 'premium'),
    ('womens', 'Modern Minimalist', 'Soft Tailored Daily',
     'Oversized blazer, straight-leg trousers, low loafers. Quietly powerful.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+3',
     array['XS','S','M','L'], array['minimalist','classic'], array['neutrals'], array['work','casual'], 'mid'),
    ('womens', 'Modern Minimalist', 'Monochrome Errands',
     'Cropped sweater, matching wide-leg pants, clean white sneakers.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+4',
     array['XS','S','M','L','XL','XXL'], array['minimalist'], array['monochrome','neutrals'], array['casual'], 'budget'),
    ('womens', 'Modern Minimalist', 'Slip & Knit Pair',
     'Bias-cut slip skirt under an oversized rib knit. Day-to-dinner reduction.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+5',
     array['XS','S','M','L'], array['minimalist'], array['monochrome'], array['going_out','casual'], 'mid'),
    ('womens', 'Modern Minimalist', 'Studio Black',
     'Black turtleneck, black wide trousers, black ballet flats. A working uniform.',
     'https://placehold.co/600x800?text=Womens+Modern+Minimalist+6',
     array['XS','S','M','L','XL'], array['minimalist'], array['monochrome'], array['work','casual'], 'mid'),

    -- ============================================================
    -- WOMEN'S — Classic Preppy
    -- ============================================================
    ('womens', 'Classic Preppy', 'Tennis Club Twinset',
     'Cream tennis sweater over a collared shirt and pleated skirt. Match-point energy.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+1',
     array['XS','S','M','L'], array['preppy','classic'], array['neutrals','jewel_tones'], array['casual'], 'mid'),
    ('womens', 'Classic Preppy', 'Heritage Loafer Look',
     'Tailored trousers, fine-knit polo, horsebit loafers. Old money, current calendar.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+2',
     array['XS','S','M','L','XL'], array['preppy','classic'], array['neutrals'], array['work','formal'], 'mid'),
    ('womens', 'Classic Preppy', 'The Cable Cardi',
     'Chunky cable cardigan, white tee, dark denim. Coffee shop or quad equally fine.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+3',
     array['XS','S','M','L','XL'], array['preppy'], array['jewel_tones','neutrals'], array['casual'], 'budget'),
    ('womens', 'Classic Preppy', 'Yacht Day Pleat',
     'Crisp white blouse, pleated knee-length skirt, navy ballet flats.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+4',
     array['XS','S','M','L'], array['preppy','classic'], array['neutrals'], array['casual','formal'], 'premium'),
    ('womens', 'Classic Preppy', 'Boardroom Pearls',
     'Tweed jacket over a silk blouse and tailored trousers. Pearls optional but encouraged.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+5',
     array['XS','S','M','L','XL'], array['preppy','classic'], array['neutrals','jewel_tones'], array['work','formal'], 'premium'),
    ('womens', 'Classic Preppy', 'Garden Party Shift',
     'Pastel shift dress, slim belt, kitten-heel slingbacks. For lawns with cake on them.',
     'https://placehold.co/600x800?text=Womens+Classic+Preppy+6',
     array['XS','S','M','L'], array['preppy'], array['pastels','jewel_tones'], array['formal','casual'], 'mid'),

    -- ============================================================
    -- WOMEN'S — Streetwear Casual
    -- ============================================================
    ('womens', 'Streetwear Casual', 'City Block Set',
     'Cropped logo hoodie, parachute pants, chunky low-top sneakers.',
     'https://placehold.co/600x800?text=Womens+Streetwear+1',
     array['XS','S','M','L'], array['streetwear'], array['brights','monochrome'], array['casual','going_out'], 'mid'),
    ('womens', 'Streetwear Casual', 'Athflow After-Class',
     'Matching sweatset, white socks pulled up, retro runners.',
     'https://placehold.co/600x800?text=Womens+Streetwear+2',
     array['XS','S','M','L','XL'], array['athleisure','streetwear'], array['monochrome'], array['casual','athletic'], 'budget'),
    ('womens', 'Streetwear Casual', 'Cargo & Crop',
     'Cargo pants, crop tank, oversized denim jacket on standby.',
     'https://placehold.co/600x800?text=Womens+Streetwear+3',
     array['XS','S','M','L'], array['streetwear'], array['monochrome','neutrals'], array['going_out','casual'], 'mid'),
    ('womens', 'Streetwear Casual', 'Court-Side Stunner',
     'Bright zip-front jacket, pleated tennis skirt, statement sneakers.',
     'https://placehold.co/600x800?text=Womens+Streetwear+4',
     array['XS','S','M','L'], array['streetwear','athleisure'], array['brights'], array['casual','athletic'], 'mid'),
    ('womens', 'Streetwear Casual', 'Oversize Hoodie Hours',
     'Oversized graphic hoodie, bike shorts, ankle socks, low-rise sneakers.',
     'https://placehold.co/600x800?text=Womens+Streetwear+5',
     array['XS','S','M','L','XL','XXL'], array['streetwear','athleisure'], array['monochrome'], array['casual'], 'budget'),
    ('womens', 'Streetwear Casual', 'Tech Bodycon',
     'High-shine compression set under an open shell jacket. Studio to street.',
     'https://placehold.co/600x800?text=Womens+Streetwear+6',
     array['XS','S','M','L'], array['athleisure','streetwear'], array['brights','monochrome'], array['athletic','going_out'], 'premium'),

    -- ============================================================
    -- WOMEN'S — Bohemian Relaxed
    -- ============================================================
    ('womens', 'Bohemian Relaxed', 'Sunset Tier Dress',
     'Tiered cotton maxi in rust, layered necklaces, leather sandals.',
     'https://placehold.co/600x800?text=Womens+Bohemian+1',
     array['XS','S','M','L'], array['bohemian'], array['earth_tones'], array['going_out','casual'], 'mid'),
    ('womens', 'Bohemian Relaxed', 'Linen Daydream',
     'Loose linen set in dusty pink, raffia tote, naked-foot mules.',
     'https://placehold.co/600x800?text=Womens+Bohemian+2',
     array['XS','S','M','L','XL'], array['bohemian','minimalist'], array['pastels','earth_tones'], array['casual'], 'mid'),
    ('womens', 'Bohemian Relaxed', 'Folk Festival Vest',
     'Embroidered vest over a flowy tank, flared jeans, suede boots.',
     'https://placehold.co/600x800?text=Womens+Bohemian+3',
     array['XS','S','M','L'], array['bohemian'], array['earth_tones'], array['going_out','casual'], 'budget'),
    ('womens', 'Bohemian Relaxed', 'Wildflower Wrap',
     'Floral wrap dress in pastels, denim jacket on the shoulders, soft sandals.',
     'https://placehold.co/600x800?text=Womens+Bohemian+4',
     array['XS','S','M','L','XL'], array['bohemian'], array['pastels','earth_tones'], array['casual','going_out'], 'mid'),
    ('womens', 'Bohemian Relaxed', 'Cottage Crochet',
     'Crochet cardigan over a simple slip dress, ankle boots, woven bag.',
     'https://placehold.co/600x800?text=Womens+Bohemian+5',
     array['XS','S','M','L'], array['bohemian'], array['earth_tones','pastels'], array['casual'], 'budget'),
    ('womens', 'Bohemian Relaxed', 'Salt Air Maxi',
     'Ivory cotton maxi dress, woven belt, shell earrings, espadrilles.',
     'https://placehold.co/600x800?text=Womens+Bohemian+6',
     array['XS','S','M','L'], array['bohemian','minimalist'], array['pastels','earth_tones'], array['going_out','casual'], 'premium'),

    -- ============================================================
    -- WOMEN'S — Polished Edgy
    -- ============================================================
    ('womens', 'Polished Edgy', 'Leather Blazer Hour',
     'Soft leather blazer, silk camisole, tailored black trousers, pointed pumps.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+1',
     array['XS','S','M','L'], array['edgy','classic'], array['monochrome'], array['going_out','work'], 'premium'),
    ('womens', 'Polished Edgy', 'Slip Dress After Dark',
     'Bias-cut satin slip dress in deep wine, ankle-strap heels, structured clutch.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+2',
     array['XS','S','M','L'], array['edgy'], array['jewel_tones','monochrome'], array['going_out','formal'], 'mid'),
    ('womens', 'Polished Edgy', 'Power Suit Noir',
     'Sharp black double-breasted suit, no shirt, slicked-back hair.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+3',
     array['XS','S','M','L','XL'], array['edgy','classic'], array['monochrome'], array['work','formal'], 'premium'),
    ('womens', 'Polished Edgy', 'Velvet Cocktail',
     'Emerald velvet mini, sheer tights, pointed booties, gold drop earrings.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+4',
     array['XS','S','M','L'], array['edgy','classic'], array['jewel_tones'], array['going_out','formal'], 'premium'),
    ('womens', 'Polished Edgy', 'Studded Sunday',
     'Studded leather jacket, plain white tee, vinyl trousers, ankle boots.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+5',
     array['XS','S','M','L'], array['edgy'], array['monochrome'], array['going_out','casual'], 'mid'),
    ('womens', 'Polished Edgy', 'Sharp Tailor Set',
     'Sapphire pantsuit, mock-neck shell, square-toe heels. Boardroom with teeth.',
     'https://placehold.co/600x800?text=Womens+Polished+Edgy+6',
     array['XS','S','M','L','XL'], array['edgy','classic'], array['jewel_tones'], array['work','formal'], 'mid');
